version: '3'
services:
  api:
    build: ./
    image: geosocio/core
    links:
      - http-cache
    env_file:
      - .env
    ports:
      - 8888:80
    volumes:
      - ./:/var/www:cached
  http-cache:
    image: geosocio/trafficserver
