version: '3'
services:
  api:
    build: ./
    ports:
      - '8888:80'
    volumes:
      - ./:/var/www:cached
    links:
      - database
  database:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'geosocio'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
