version: '3'
services:
    api:
        ports:
            - '80:80'
        build: ./
        image: 192.168.99.101:5000/geosocio
        volumes:
            - './:/var/www'
        deploy:
            replicas: 1
