version: '3'
services:
  api:
    build: ./
    networks:
      - default
      - geosocio
    env_file:
      - .env
    volumes:
      - ./:/var/www:cached
networks:
  geosocio:
    external:
      name: geosocio_default
