version: '3'
services:
  api:
    build: ./
    image: geosocio/core
    env_file:
      - .env
    ports:
      - 8888:80
    volumes:
      - ./:/var/www:cached
  build:
    image: composer
    env_file:
      - .env
    volumes:
      - ./:/app:cached
    command: 'composer install'
