default:
    resource: '@Core/Controller/DefaultController.php'
    type:     annotation

auth:
    resource: '@Core/Controller/AuthController.php'
    type:     annotation

user:
    resource: '@Core/Controller/UserController.php'
    type:     annotation

place:
    resource: '@Core/Controller/PlaceController.php'
    type:     annotation
