# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:

services:
    geosocio.authenticated_user_resolver:
        class: GeoSocio\Core\ArgumentResolver\AuthenticatedUserResolver
        arguments:
            - '@security.token_storage'
        tags:
            - { name: controller.argument_value_resolver, priority: 100 }

    geosocio.input_resolver:
        class: GeoSocio\Core\ArgumentResolver\InputResolver
        arguments:
            - '@serializer'
        tags:
            - { name: controller.argument_value_resolver }

    geosocio.controller:
        abstract:  true
        arguments:
            - '@geosocio.denormalizer'
            - '@doctrine'

    geosocio.controller_default:
        parent: geosocio.controller
        class: GeoSocio\Core\Controller\DefaultController

    geosocio.controller_auth:
        parent: geosocio.controller
        class: GeoSocio\Core\Controller\AuthController
        arguments:
            - "@geosocio.verification_manager"
            - '@lexik_jwt_authentication.jwt_manager'

    geosocio.controller_user:
        parent: geosocio.controller
        class: GeoSocio\Core\Controller\UserController
        arguments:
            - "@geosocio.verification_manager"
            - '@geosocio.place_finder'

    geosocio.controller_place:
        parent: geosocio.controller
        class: GeoSocio\Core\Controller\PlaceController

    geosocio.controller_site:
        parent: geosocio.controller
        class: GeoSocio\Core\Controller\SiteController

    geosocio.denormalizer:
        class: GeoSocio\Core\Serializer\Denormalizer
        arguments:
            - '@serializer'
            - '@validator'
            - '@security.token_storage'

    geosocio.return_listener:
        class: GeoSocio\Core\EventListener\ReturnListener
        arguments:
            - '@serializer'
            - '@serializer'
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.view }
            - { name: kernel.event_listener, event: kernel.exception }

    geosocio.tree_maker:
        class: GeoSocio\Core\EventListener\TreeMaker
        public: false
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    geosocio.code_authenticator:
        class: GeoSocio\Core\Security\CodeAuthenticator
        arguments:
            - '@geosocio.denormalizer'
            - '@doctrine'
            - '@security.http_utils'

    geosocio.verification_manager:
         class: GeoSocio\Core\Utils\User\VerificationManager

    geosocio.verification_email:
        class: GeoSocio\Core\Utils\User\EmailVerification
        public: false
        arguments:
            - '@doctrine'
            - '@ircmaxell.random'
            - '@geosocio.dispatcher_email'
        tags:
            - { name: geosocio.verification, type: email }

    geosocio.dispatcher_email:
        class: GeoSocio\Core\Utils\Dispatcher\EmailDispatcher
        arguments:
            - '@sendgrid'

    geosocio.place_finder:
        class: GeoSocio\Core\Utils\PlaceFinder
        arguments:
            - '@doctrine'
            - '@geosocio.client_mapzen_search'
            - '@geosocio.client_mapzen_whos_on_first'

    sendgrid:
        class: SendGrid
        arguments:
            - '%sendgrid_api_key%'

    ircmaxell.random_factory:
        class: RandomLib\Factory

    ircmaxell.random:
        class: RandomLib\Generator
        factory: ["@ircmaxell.random_factory", getMediumStrengthGenerator]

    # prawnsalad.nexmo:
    #     class: NexmoMessage
    #     arguments:
    #         - '%nexmo_api_key%'
    #         - '%nexmo_api_secret%'

    geosocio.client_mapzen_search:
        class: GeoSocio\Core\Client\Mapzen\Search
        arguments:
            - '@guzzlehttp.client_mapzen_search'
            - '@serializer'

    geosocio.client_mapzen_whos_on_first:
        class: GeoSocio\Core\Client\Mapzen\WhosOnFirst
        arguments:
            - '@guzzlehttp.client_mapzen_whos_on_first'
            - '@serializer'

    geosocio.serializer_mapzen_search:
        class: GeoSocio\Core\Serializer\Mapzen\SearchDenormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    geosocio.serializer_mapzen_whos_on_first:
        class: GeoSocio\Core\Serializer\Mapzen\WhosOnFirstDenormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    guzzlehttp.client_mapzen_search:
        class: GuzzleHttp\Client
        arguments:
            -
                base_url: https://search.mapzen.com/v1/
                defaults:
                    query:
                        api_key: '%mapzen_api_key%'

    guzzlehttp.client_mapzen_whos_on_first:
        class: GuzzleHttp\Client
        arguments:
            -
                base_url: https://whosonfirst-api.mapzen.com
                defaults:
                    query:
                        api_key: '%mapzen_api_key%'
